version: "1"

services:
    db:
        image: postgres:14beta2-alpine3.14
        restart: always
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSTGRES_DB: go-jwt-auth
        ports:
            - "5432:5432"
